In [1]:
import numpy as np
import math
import pandas as pd
import seaborn as sns
import scipy.stats as ss

# Задача 1

О непрерывной равномерно распределённой случайной величине $B$ известно, что её дисперсия равна $0.2$. Можно ли найти правую границу величины $B$ и её среднее значение зная, что левая граница равна $0.5$? Если да, найдите их.

In [2]:
d = 0.2
a = 0.5

b = math.sqrt(12*d)+a
print('Правая граница для B равна - ', b)

m = (b+a)/2 
print('Математическое ожидание для B равно - ', m)

Правая граница для B равна -  2.049193338482967
Математическое ожидание для B равно -  1.2745966692414834


$$D[X] = {{(b-a)^2}\over{12}}$$


$$M[X] = {{b+a}\over{2}}$$

# Задача 2

На сколько сигм (средних квадратических отклонений) отклоняется рост человека, равный $190$ см, от математического ожидания роста в популяции, в которой $M(X) = 178$ и $D(X) = 25$?

In [3]:
x =  190
m_x = 178
d_x = 25
a = m_x
sigma = math.sqrt(d_x)



print('Отклонение составляет - ', (x-a)/sigma, 'сигм')

Отклонение составляет -  2.4 сигм


# Задача 3

Рост взрослого населения города $X$ имеет нормальное распределение, причём, средний рост равен $174$ см, а среднее квадратическое отклонение равно $8$ см. С помощью правил стандартного отклонения, двух и трёх сигм посчитайте, какова вероятность того, что случайным образом выбранный взрослый человек имеет рост:

* больше $182$ см?
* больше $190$ см?
* от $166$ см до $190$ см?
* от $166$ см до $182$ см?
* от $158$ см до $190$ см?
* не выше $150$ см или не ниже $190$ см?
* не выше $150$ см или не ниже $198$ см?
* ниже $166$ см?

In [4]:
a = 174
sigma = 8

standart_ = np.array([a - sigma, a + sigma])
two_sigmas = np.array([a - 2 * sigma, a + 2 * sigma])
three_sigmas = np.array([a - 3 * sigma, a + 3 * sigma])

In [5]:
def between(dowm, up, x, turn):
    if turn == '>':
        if x>=dowm and x<up:
            return True
        else: 
            return False
    if turn == '<':
        if x>dowm and x<=up:
            return True
        else: 
            return False
    if turn == '>=':
        if x>=dowm and x<=up:
            return True
        else: 
            return False
    if turn == '<=':
        if x>=dowm and x<=up:
            return True
        else: 
            return False

In [6]:
def pr_sector(x, turn, standart_ = standart_, two_sigmas=two_sigmas, three_sigmas=three_sigmas):
    

    if between(-np.inf, three_sigmas[0], x, turn):
        pr_sector = 0
    if between(three_sigmas[1], np.inf, x, turn):
        pr_sector = 6
    if between(three_sigmas[0], two_sigmas[0], x, turn):
        pr_sector = 1
    if between(two_sigmas[1], three_sigmas[1], x, turn):
        pr_sector = 5
    if between(two_sigmas[0], standart_[0], x, turn):
        pr_sector = 2
    if between(standart_[1], two_sigmas[1], x, turn):
        pr_sector = 4
    if between(standart_[0], standart_[1], x, turn):
        pr_sector = 3
        
    return pr_sector

In [7]:
def probability(x, turn_x, y=False, turn_y=False, if_or = False):
    
    prob_in_sector = np.array([0.15, 2.35, 13.5, 68, 13.5, 2.35, 0.15])
    pr_sector_down = pr_sector(x, turn_x)
    if y != False and turn_y != False:
        pr_sector_up = pr_sector(y, turn_y)
    
    if if_or == False:
        if y == False and turn_y == False:
            if turn_x == '>':
                pr = np.sum(prob_in_sector[pr_sector_down::])
            elif turn_x == '<':
                pr = np.sum(prob_in_sector[:pr_sector_down+1:])
        else:
            pr = np.sum(prob_in_sector[pr_sector_down:pr_sector_up+1:])
    
    elif  if_or == True:
        pr = np.sum(prob_in_sector[:pr_sector_down+1:])+np.sum(prob_in_sector[pr_sector_up::])
    
    return pr

In [8]:
print(standart_)
print(two_sigmas)
print(three_sigmas)

[166 182]
[158 190]
[150 198]


In [9]:
probability_ = probability(182, '>')
print('Вероятность, что человек имеет рост {} - {}%'.format('больше 182 см', round(probability_, 2)))

Вероятность, что человек имеет рост больше 182 см - 16.0%


Пояснение: рост свыше $182$ см входит в диапазон $2\sigma$ и далее справа, т.е. ${{100-68}\over{2}}\%$

In [10]:
probability_ = probability(190, '>')
print('Вероятность, что человек имеет рост {} - {}%'.format('больше 190 см', round(probability_, 2)))

Вероятность, что человек имеет рост больше 190 см - 2.5%


Пояснение: рост свыше $190$ см входит в диапазон $3\sigma$ и далее справа, т.е. ${{100-95}\over{2}}\%$

In [11]:
probability_ = probability(166, '>', 190, '<')
print('Вероятность, что человек имеет рост {} - {}%'.format('от 166 до 190 см', round(probability_, 2)))

Вероятность, что человек имеет рост от 166 до 190 см - 81.5%


Пояснение: рост от $166$ до $190$ см входит в диапазон от стандартного отклонения до $2\sigma$ справа, т.е. ${68+}{{95-68}\over{2}}\%$

In [12]:
probability_ = probability(166, '>', 182, '<')
print('Вероятность, что человек имеет рост {} - {}%'.format('от 166 до 182 см', round(probability_, 2)))

Вероятность, что человек имеет рост от 166 до 182 см - 68.0%


Пояснение: рост от $166$ до $182$ см входит в диапазон стандартного отклонения, т.е. $68\%$

In [13]:
probability_ = probability(158, '>', 190, '<')
print('Вероятность, что человек имеет рост {} - {}%'.format('от 158 до 190 см', round(probability_, 2)))

Вероятность, что человек имеет рост от 158 до 190 см - 95.0%


Пояснение: рост от $158$ до $190$ см входит в диапазон $2\sigma$, т.е. $95\%$

In [14]:
probability_ = probability(150, '<=', 190, '>=', if_or = True)
print('Вероятность, что человек имеет рост {} - {}%'.format('не выше 150 и не ниже 190 см', round(probability_, 2)))

Вероятность, что человек имеет рост не выше 150 и не ниже 190 см - 18.5%


Пояснение: рост не выше $150$ и не ниже $190$ см входит в диапазон $3\sigma$ и далее слева и $2\sigma$ и далее справа, т.е. ${{100-95}\over{2}}+{{100-68}\over{2}}\%$

In [15]:
probability_ = probability(150, '<=', 198, '>=', if_or = True)
print('Вероятность, что человек имеет рост {} - {}%'.format('не выше 150 и не ниже 198 см', round(probability_, 2)))

Вероятность, что человек имеет рост не выше 150 и не ниже 198 см - 5.0%


Пояснение: рост не выше $150$ и не ниже $190$ см входит в диапазон $3\sigma$ и далее слева и $3\sigma$ и далее справа, т.е. ${{100-95}\over{2}}+{{100-95}\over{2}}\%$

In [16]:
probability_ = probability(166, '<')
print('Вероятность, что человек имеет рост {} - {}%'.format('ниже 166 см', round(probability_, 2)))

Вероятность, что человек имеет рост ниже 166 см - 16.0%


Пояснение: рост ниже $166$ см входит в диапазон $2\sigma$ и далее слева, т.е. ${{100-68}\over{2}}\%$